import {chromium,expect} from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";
const root=path.resolve(".."),base="http://127.0.0.1:8000",out=path.join(root,"data/qa-trading");
await fs.mkdir(out,{recursive:true});
const credentials=JSON.parse(await fs.readFile(path.join(root,"data/tracy-owner.json"),"utf8"));
const demo=JSON.parse(await fs.readFile(path.join(root,"data/trading-demo.json"),"utf8"));
const browser=await chromium.launch({channel:"chrome",headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1050}});
const page=await context.newPage(),errors=[],resume=process.argv.includes("--resume"),report=resume?JSON.parse(await fs.readFile(path.join(out,"report.json"),"utf8")):{started_at:new Date().toISOString(),checks:[]};
page.on("pageerror",e=>errors.push(e.message));
const check=t=>{if(!report.checks.includes(t))report.checks.push(t);console.log(t)};
async function noOverflow(){expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBeTruthy()}
try{
 await page.goto(base);
 await page.getByLabel("Email",{exact:true}).fill(credentials.email);
 await page.getByLabel("Password",{exact:true}).fill(credentials.password);
 await page.getByRole("button",{name:"Sign in",exact:true}).click();
 await expect(page.getByRole("heading",{name:"Is your strategy still working?"})).toBeVisible();
 await expect(page.getByText("SOL Momentum",{exact:false}).first()).toBeVisible();
 await page.screenshot({path:path.join(out,"overview-desktop.png"),fullPage:true});
 await noOverflow();check("Strategy overview, calculated performance, health and logo palette");
 if(!resume){
 await page.goto(base+"/strategies/"+demo[0].strategy_id);
 await page.getByText(/Why .*View formula/).click();
 await expect(page.getByText("clamp(50 + live_return_pct * 5, 0, 100)",{exact:true})).toBeVisible();
 await page.screenshot({path:path.join(out,"strategy-desktop.png"),fullPage:true});
 await page.getByRole("button",{name:"Guardrails",exact:true}).click();
 await page.getByRole("button",{name:"Submit oversized demo order"}).click();
 await expect(page.getByRole("heading",{name:"Trading intent & decision"})).toBeVisible();
 await expect(page.getByText("max trade size",{exact:true})).toBeVisible();
 await expect(page.getByText("No fill was executed.",{exact:false})).toBeVisible();
 check("Oversized order rejected by the backend before execution");
 await page.goto(base+"/strategies/new");
 await page.getByLabel("Strategy name",{exact:true}).fill("Browser v3 QA "+Date.now());
 await page.getByLabel("Agent identity").selectOption("tracy_v3_momentum");
 await page.getByLabel("Human approval above",{exact:false}).fill("1");
 await page.getByRole("button",{name:"Create strategy",exact:true}).click();
 await expect(page.getByRole("button",{name:"Run backtest",exact:true})).toBeVisible();
 const sid=page.url().split("/").at(-1);report.strategy_id=sid;
 await page.getByRole("button",{name:"Run backtest",exact:true}).click();
 await expect(page.getByRole("button",{name:"Deploy paper",exact:true})).toBeEnabled();
 await page.getByRole("button",{name:"Deploy paper",exact:true}).click();
 await expect(page.getByRole("button",{name:"Advance 24 bars",exact:true})).toBeEnabled();
 await page.getByRole("button",{name:"Advance 24 bars",exact:true}).click();
 await expect(page.getByRole("link",{name:"Review & approve trade"})).toBeVisible();
 await page.getByRole("link",{name:"Review & approve trade"}).click();
 await expect(page.getByRole("button",{name:"Approve this trade"})).toBeVisible();
 await page.getByLabel("Decision note").fill("Browser test: paper order only");
 await page.getByRole("button",{name:"Approve this trade"}).click();
 await expect(page.getByRole("link",{name:"Open Trading Proof"})).toBeVisible();
 await page.getByRole("link",{name:"Open Trading Proof"}).click();
 report.proof_url=page.url();
 await page.getByRole("button",{name:"Verify proof now"}).click();
 await expect(page.locator("pre").filter({hasText:'"browser_hash_signature_chain": true'})).toBeVisible();
 const downloadEvent=page.waitForEvent("download");
 await page.getByRole("button",{name:"Download proof & chain"}).click();
 await (await downloadEvent).saveAs(path.join(out,"trading-proof.json"));
 await page.screenshot({path:path.join(out,"proof-desktop.png"),fullPage:true});
 check("Browser create, test, deploy, human approval, fill, readback and browser proof verification");
 await page.goto(base+"/strategies/"+sid);
 await page.getByRole("button",{name:"Pause & adapt"}).click();
 await page.getByLabel("Change note").fill("Reduce exposure after reviewing performance");
 await page.getByLabel("Capital per entry",{exact:false}).fill("20");
 await page.getByRole("button",{name:"Save new version"}).click();
 await expect(page.getByLabel("Strategy version")).toHaveValue("2");
 await page.getByLabel("Strategy version").selectOption("1");
 await expect(page.getByRole("button",{name:"Deploy paper"})).toHaveCount(0);
 await page.getByRole("button",{name:"Trades & proofs"}).click();
 await expect(page.getByRole("link",{name:"Open proof"}).first()).toBeVisible();
 check("Version adaptation preserves the previous version's fills and evidence");
 }
 await page.goto(base+"/explore");
 await expect(page.getByRole("heading",{name:"Performance. Risk. Evidence."})).toBeVisible();
 await expect(page.getByRole("link",{name:"View agent"}).first()).toBeVisible();
 await page.screenshot({path:path.join(out,"exchange-desktop.png"),fullPage:true});
 await page.getByRole("link",{name:"View agent"}).first().click();
 await expect(page.getByRole("heading",{name:"Verified action history"})).toBeVisible();
 await page.goto(base+"/compare?ids="+demo.map(d=>d.strategy_id).join(","));
 await expect(page.getByRole("rowheader",{name:"Backtest/live gap",exact:true})).toBeVisible();
 await page.screenshot({path:path.join(out,"compare-desktop.png"),fullPage:true});
 await noOverflow();check("Published profiles, paper evidence disclosure and two-agent comparison");
 await page.goto(base+"/degradation");
 await expect(page.getByRole("heading",{name:"Degradation alerts",exact:true})).toBeVisible();
 await expect(page.getByRole("button",{name:"Acknowledge",exact:true}).first()).toBeVisible();
 await page.getByRole("button",{name:"Acknowledge",exact:true}).first().click();
 await expect(page.getByRole("button",{name:"Acknowledged",exact:true}).first()).toBeVisible();
 await page.goto(base+"/infrastructure");
 await expect(page.getByRole("heading",{name:"Guardrails & infrastructure",exact:true})).toBeVisible();
 await page.getByRole("link",{name:/Human approvals/}).click();
 await expect(page.getByRole("heading",{name:"Human approvals",exact:true})).toBeVisible();
 check("Alert acknowledgement and preserved control-layer navigation");
 await page.setViewportSize({width:390,height:844});
 for(const [url,name]of [["/","overview-mobile"],["/strategies/"+demo[0].strategy_id,"strategy-mobile"],["/explore","exchange-mobile"]]){
  await page.goto(base+url);await page.waitForLoadState("networkidle");await noOverflow();
  await page.screenshot({path:path.join(out,name+".png"),fullPage:true});
 }
 check("Mobile layouts have no document-level horizontal overflow");
 if(errors.length)throw new Error(errors.join("\n"));
 report.passed=true;report.browser_errors=errors;
}finally{
 await fs.writeFile(path.join(out,"report.json"),JSON.stringify(report,null,2));
 await browser.close();
}
